#-------------------------------------------------------------------------------
# Librairies
#-------------------------------------------------------------------------------

import os
from pathlib import Path

#-------------------------------------------------------------------------------
# Functions
#-------------------------------------------------------------------------------

def index_to_str(j):
  '''
  An integer is converted to a float with 3 components
  '''
  if j < 10:
      j_str = '00'+str(j)
  elif 10 <= j and j < 100:
      j_str = '0'+str(j)
  else :
      j_str = str(j)
  return j_str

#-------------------------------------------------------------------------------

def Sort_vtk(dict_pp):
    '''
    Sort .vtk files generated by MOOSE.
    '''
    j = 0
    j_str = index_to_str(j)
    filepath = Path('PF_Cement_Solidification_other_'+j_str+'.pvtu')
    while filepath.exists():
        for i_proc in range(6):
            os.rename('PF_Cement_Solidification_other_'+j_str+'_'+str(i_proc)+'.vtu','vtk/PF_Cement_Solidification_other_'+j_str+'_'+str(i_proc)+'.vtu')
        os.rename('PF_Cement_Solidification_other_'+j_str+'.pvtu','vtk/PF_Cement_Solidification_other_'+j_str+'.pvtu')
        j = j + 1
        j_str = index_to_str(j)
        filepath = Path('PF_Cement_Solidification_other_'+j_str+'.pvtu')

    # save the last iteration
    dict_pp['last_j_str'] = index_to_str(j-1)
